apiVersion: v1
kind: Secret
metadata:
  name: opensearch-admin-credential # default opensearch admin credentials for clusteroutput
type: Opaque
data:
  username: YWRtaW4= # admin
  password: YWRtaW4= # admin
