apiVersion: v1
kind: Service
metadata:
  name: opensearch-api
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 9200  
  selector:
    opster.io/opensearch-cluster: logging-cluster
