apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-operator-root
spec:
  globalFilters:
    - enhanceK8s: {}
  controlNamespace: logging
  filters:
    - stdout:
        output_type: json
  fluentbit:
    metrics:
      serviceMonitor: false # set to true if you installed the metrics component and would like to gather metrics from fluentbit
  fluentd:
    metrics:
      serviceMonitor: false # set to true if you installed the metrics component and would like to gather metrics from fluentd